M48
; DRILL file {KiCad 7.0.7-146-g6b43bb8fe3} date Fri Oct  6 16:17:02 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-06T16:17:02+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-146-g6b43bb8fe3
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C17.000
%
G90
G05
T1
X76.546Y-93.545
X218.546Y-93.545
T2
X205.546Y-97.545
T3
X187.546Y-92.545
T0
M30
